language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_script:
  - echo "<settings><servers><server><id>\${env.FTP_RELEASES_ID}</id><username>\${env.FTP_RELEASES_USER}</username><password>\${env.FTP_RELEASES_PASSWORD}</password></server><server><id>\${env.FTP_SNAPSHOTS_ID}</id><username>\${env.FTP_SNAPSHOTS_USER}</username><password>\${env.FTP_SNAPSHOTS_PASSWORD}</password></server><server><id>\${env.FTP_SITE_ID}</id><username>\${env.FTP_SITE_USER}</username><password>\${env.FTP_SITE_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
script:
  - mvn clean verify
after_success:
  - ./.scripts/deploy-site.sh
  - ./.scripts/deploy.sh
