name: Doc deployment

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch on which the site will be deployed'
        required: true
        type: string
      host:
        description: 'Host where the site will be deployed'
        required: true
        type: string
    secrets:
      DEPLOY_DOCS_SITE:
        description: 'URL to deploy the site'
        required: true
      DEPLOY_DOCS_USER:
        description: 'User for the site server'
        required: true
      DEPLOY_DOCS_PASSWORD:
        description: 'Password for the site server'
        required: true

jobs:
  setup:
    name: Deployment preparation
    outputs:
      branchName: ${{ steps.extract_branch.outputs.branchName }}
    runs-on: ubuntu-latest

    steps:
    - name: Register SSH host
      uses: bernardo-mg/ssh-host-register-action@v1
      with:
        host: ${{ inputs.host }}
    - name: Extract branch name
      uses: bernardo-mg/extract-branch-name-action@v1
      id: extract_branch

  deploy:
    name: Deployment
    needs: setup
    if: ${{ needs.setup.outputs.branchName == inputs.branch }}
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: 'maven'
    - name: Set up Maven settings for site deployment
      uses: bernardo-mg/maven-site-deployment-settings-action@v1
      with:
        siteId: site
        siteUrl: ${{ secrets.DEPLOY_DOCS_SITE }}
        user: ${{ secrets.DEPLOY_DOCS_USER }}
        password: ${{ secrets.DEPLOY_DOCS_PASSWORD }}
    - name: Generate docs
      run: mvn verify site -B
    - name: Deploy docs
      run: mvn site:deploy -B -P deployment-site -DskipTests --settings site_settings.xml
